// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/video/config.proto (package wave.v1.video, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/video/config.proto.
 */
export const file_wave_v1_video_config: GenFile = /*@__PURE__*/
  fileDesc("Chp3YXZlL3YxL3ZpZGVvL2NvbmZpZy5wcm90bxINd2F2ZS52MS52aWRlbyIbCgtWaWRlb0NvbmZpZxIMCgRwYXRoGAEgASgJQiZaJGN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvd2F2ZS92MS92aWRlb2IGcHJvdG8z");

/**
 * @generated from message wave.v1.video.VideoConfig
 */
export type VideoConfig = Message<"wave.v1.video.VideoConfig"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message wave.v1.video.VideoConfig.
 * Use `create(VideoConfigSchema)` to create a new message.
 */
export const VideoConfigSchema: GenMessage<VideoConfig> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_config, 0);

