// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file granit/v1/disk/config.proto (package granit.v1.disk, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file granit/v1/disk/config.proto.
 */
export const file_granit_v1_disk_config: GenFile = /*@__PURE__*/
  fileDesc("ChtncmFuaXQvdjEvZGlzay9jb25maWcucHJvdG8SDmdyYW5pdC52MS5kaXNrIngKCkRpc2tDb25maWcSKgoGZm9ybWF0GAEgASgOMhouZ3Jhbml0LnYxLmRpc2suRGlza0Zvcm1hdBIMCgRwYXRoGAIgASgJEhAKCHJlYWRvbmx5GAMgASgIEgwKBHNpemUYBCABKAMSEAoIcmVwbGljYXMYBSABKAMqOAoKRGlza0Zvcm1hdBITCg9ESVNLX0ZPUk1BVF9SQVcQABIVChFESVNLX0ZPUk1BVF9RQ09XMhABQidaJWN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvZ3Jhbml0L3YxL2Rpc2tiBnByb3RvMw");

/**
 * @generated from message granit.v1.disk.DiskConfig
 */
export type DiskConfig = Message<"granit.v1.disk.DiskConfig"> & {
  /**
   * @generated from field: granit.v1.disk.DiskFormat format = 1;
   */
  format: DiskFormat;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: bool readonly = 3;
   */
  readonly: boolean;

  /**
   * @generated from field: int64 size = 4;
   */
  size: bigint;

  /**
   * @generated from field: int64 replicas = 5;
   */
  replicas: bigint;
};

/**
 * Describes the message granit.v1.disk.DiskConfig.
 * Use `create(DiskConfigSchema)` to create a new message.
 */
export const DiskConfigSchema: GenMessage<DiskConfig> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_config, 0);

/**
 * @generated from enum granit.v1.disk.DiskFormat
 */
export enum DiskFormat {
  /**
   * @generated from enum value: DISK_FORMAT_RAW = 0;
   */
  RAW = 0,

  /**
   * @generated from enum value: DISK_FORMAT_QCOW2 = 1;
   */
  QCOW2 = 1,
}

/**
 * Describes the enum granit.v1.disk.DiskFormat.
 */
export const DiskFormatSchema: GenEnum<DiskFormat> = /*@__PURE__*/
  enumDesc(file_granit_v1_disk_config, 0);

