// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file granit/v1/disk/message.proto (package granit.v1.disk, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { DiskConfig } from "./config_pb";
import { file_granit_v1_disk_config } from "./config_pb";
import type { DiskCluster } from "./cluster_pb";
import { file_granit_v1_disk_cluster } from "./cluster_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file granit/v1/disk/message.proto.
 */
export const file_granit_v1_disk_message: GenFile = /*@__PURE__*/
  fileDesc("ChxncmFuaXQvdjEvZGlzay9tZXNzYWdlLnByb3RvEg5ncmFuaXQudjEuZGlzayKOAQoERGlzaxIPCgdyZXFub2RlGAEgASgJEgwKBG5vZGUYAiABKAkSLAoHY2x1c3RlchgDIAEoCzIbLmdyYW5pdC52MS5kaXNrLkRpc2tDbHVzdGVyEioKBmNvbmZpZxgEIAEoCzIaLmdyYW5pdC52MS5kaXNrLkRpc2tDb25maWcSDQoFZXJyb3IYCCABKAkiGAoKR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSIxCgtHZXRSZXNwb25zZRIiCgRkaXNrGAEgASgLMhQuZ3Jhbml0LnYxLmRpc2suRGlzayINCgtMaXN0UmVxdWVzdCIzCgxMaXN0UmVzcG9uc2USIwoFZGlza3MYASADKAsyFC5ncmFuaXQudjEuZGlzay5EaXNrIjsKDUNyZWF0ZVJlcXVlc3QSKgoGY29uZmlnGAEgASgLMhouZ3Jhbml0LnYxLmRpc2suRGlza0NvbmZpZyIcCg5DcmVhdGVSZXNwb25zZRIKCgJpZBgBIAEoCSJHCg1VcGRhdGVSZXF1ZXN0EgoKAmlkGAEgASgJEioKBmNvbmZpZxgCIAEoCzIaLmdyYW5pdC52MS5kaXNrLkRpc2tDb25maWciEAoOVXBkYXRlUmVzcG9uc2UiGwoNRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCSIQCg5EZWxldGVSZXNwb25zZUInWiVjdGh1bC5pby9jdGh1bC9wa2cvYXBpL2dyYW5pdC92MS9kaXNrYgZwcm90bzM", [file_granit_v1_disk_config, file_granit_v1_disk_cluster]);

/**
 * @generated from message granit.v1.disk.Disk
 */
export type Disk = Message<"granit.v1.disk.Disk"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * @generated from field: granit.v1.disk.DiskCluster cluster = 3;
   */
  cluster?: DiskCluster;

  /**
   * core prop
   *
   * @generated from field: granit.v1.disk.DiskConfig config = 4;
   */
  config?: DiskConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message granit.v1.disk.Disk.
 * Use `create(DiskSchema)` to create a new message.
 */
export const DiskSchema: GenMessage<Disk> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 0);

/**
 * @generated from message granit.v1.disk.GetRequest
 */
export type GetRequest = Message<"granit.v1.disk.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message granit.v1.disk.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 1);

/**
 * @generated from message granit.v1.disk.GetResponse
 */
export type GetResponse = Message<"granit.v1.disk.GetResponse"> & {
  /**
   * @generated from field: granit.v1.disk.Disk disk = 1;
   */
  disk?: Disk;
};

/**
 * Describes the message granit.v1.disk.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 2);

/**
 * @generated from message granit.v1.disk.ListRequest
 */
export type ListRequest = Message<"granit.v1.disk.ListRequest"> & {
};

/**
 * Describes the message granit.v1.disk.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 3);

/**
 * @generated from message granit.v1.disk.ListResponse
 */
export type ListResponse = Message<"granit.v1.disk.ListResponse"> & {
  /**
   * @generated from field: repeated granit.v1.disk.Disk disks = 1;
   */
  disks: Disk[];
};

/**
 * Describes the message granit.v1.disk.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 4);

/**
 * @generated from message granit.v1.disk.CreateRequest
 */
export type CreateRequest = Message<"granit.v1.disk.CreateRequest"> & {
  /**
   * @generated from field: granit.v1.disk.DiskConfig config = 1;
   */
  config?: DiskConfig;
};

/**
 * Describes the message granit.v1.disk.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 5);

/**
 * @generated from message granit.v1.disk.CreateResponse
 */
export type CreateResponse = Message<"granit.v1.disk.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message granit.v1.disk.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 6);

/**
 * @generated from message granit.v1.disk.UpdateRequest
 */
export type UpdateRequest = Message<"granit.v1.disk.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: granit.v1.disk.DiskConfig config = 2;
   */
  config?: DiskConfig;
};

/**
 * Describes the message granit.v1.disk.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 7);

/**
 * @generated from message granit.v1.disk.UpdateResponse
 */
export type UpdateResponse = Message<"granit.v1.disk.UpdateResponse"> & {
};

/**
 * Describes the message granit.v1.disk.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 8);

/**
 * @generated from message granit.v1.disk.DeleteRequest
 */
export type DeleteRequest = Message<"granit.v1.disk.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message granit.v1.disk.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 9);

/**
 * @generated from message granit.v1.disk.DeleteResponse
 */
export type DeleteResponse = Message<"granit.v1.disk.DeleteResponse"> & {
};

/**
 * Describes the message granit.v1.disk.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_message, 10);

