// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/serial/message.proto (package wave.v1.serial, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SerialConfig } from "./config_pb";
import { file_wave_v1_serial_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/serial/message.proto.
 */
export const file_wave_v1_serial_message: GenFile = /*@__PURE__*/
  fileDesc("Chx3YXZlL3YxL3NlcmlhbC9tZXNzYWdlLnByb3RvEg53YXZlLnYxLnNlcmlhbCJkCgZTZXJpYWwSDwoHcmVxbm9kZRgBIAEoCRIMCgRub2RlGAIgASgJEiwKBmNvbmZpZxgDIAEoCzIcLndhdmUudjEuc2VyaWFsLlNlcmlhbENvbmZpZxINCgVlcnJvchgIIAEoCSIYCgpHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIjUKC0dldFJlc3BvbnNlEiYKBnNlcmlhbBgBIAEoCzIWLndhdmUudjEuc2VyaWFsLlNlcmlhbCIfCg5Db25uZWN0UmVxdWVzdBINCgVpbnB1dBgBIAEoDCIhCg9Db25uZWN0UmVzcG9uc2USDgoGb3V0cHV0GAEgASgMIg0KC0xpc3RSZXF1ZXN0IpIBCgxMaXN0UmVzcG9uc2USOgoHc2VyaWFscxgBIAMoCzIpLndhdmUudjEuc2VyaWFsLkxpc3RSZXNwb25zZS5TZXJpYWxzRW50cnkaRgoMU2VyaWFsc0VudHJ5EgsKA2tleRgBIAEoCRIlCgV2YWx1ZRgCIAEoCzIWLndhdmUudjEuc2VyaWFsLlNlcmlhbDoCOAEiPQoNQ3JlYXRlUmVxdWVzdBIsCgZjb25maWcYASABKAsyHC53YXZlLnYxLnNlcmlhbC5TZXJpYWxDb25maWciHAoOQ3JlYXRlUmVzcG9uc2USCgoCaWQYASABKAkiSQoNVXBkYXRlUmVxdWVzdBIKCgJpZBgBIAEoCRIsCgZjb25maWcYAiABKAsyHC53YXZlLnYxLnNlcmlhbC5TZXJpYWxDb25maWciEAoOVXBkYXRlUmVzcG9uc2UiGwoNRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCSIQCg5EZWxldGVSZXNwb25zZUInWiVjdGh1bC5pby9jdGh1bC9wa2cvYXBpL3dhdmUvdjEvc2VyaWFsYgZwcm90bzM", [file_wave_v1_serial_config]);

/**
 * @generated from message wave.v1.serial.Serial
 */
export type Serial = Message<"wave.v1.serial.Serial"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * core prop
   *
   * @generated from field: wave.v1.serial.SerialConfig config = 3;
   */
  config?: SerialConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message wave.v1.serial.Serial.
 * Use `create(SerialSchema)` to create a new message.
 */
export const SerialSchema: GenMessage<Serial> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 0);

/**
 * @generated from message wave.v1.serial.GetRequest
 */
export type GetRequest = Message<"wave.v1.serial.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 1);

/**
 * @generated from message wave.v1.serial.GetResponse
 */
export type GetResponse = Message<"wave.v1.serial.GetResponse"> & {
  /**
   * @generated from field: wave.v1.serial.Serial serial = 1;
   */
  serial?: Serial;
};

/**
 * Describes the message wave.v1.serial.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 2);

/**
 * @generated from message wave.v1.serial.ConnectRequest
 */
export type ConnectRequest = Message<"wave.v1.serial.ConnectRequest"> & {
  /**
   * @generated from field: bytes input = 1;
   */
  input: Uint8Array;
};

/**
 * Describes the message wave.v1.serial.ConnectRequest.
 * Use `create(ConnectRequestSchema)` to create a new message.
 */
export const ConnectRequestSchema: GenMessage<ConnectRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 3);

/**
 * @generated from message wave.v1.serial.ConnectResponse
 */
export type ConnectResponse = Message<"wave.v1.serial.ConnectResponse"> & {
  /**
   * @generated from field: bytes output = 1;
   */
  output: Uint8Array;
};

/**
 * Describes the message wave.v1.serial.ConnectResponse.
 * Use `create(ConnectResponseSchema)` to create a new message.
 */
export const ConnectResponseSchema: GenMessage<ConnectResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 4);

/**
 * @generated from message wave.v1.serial.ListRequest
 */
export type ListRequest = Message<"wave.v1.serial.ListRequest"> & {
};

/**
 * Describes the message wave.v1.serial.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 5);

/**
 * @generated from message wave.v1.serial.ListResponse
 */
export type ListResponse = Message<"wave.v1.serial.ListResponse"> & {
  /**
   * @generated from field: map<string, wave.v1.serial.Serial> serials = 1;
   */
  serials: { [key: string]: Serial };
};

/**
 * Describes the message wave.v1.serial.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 6);

/**
 * @generated from message wave.v1.serial.CreateRequest
 */
export type CreateRequest = Message<"wave.v1.serial.CreateRequest"> & {
  /**
   * @generated from field: wave.v1.serial.SerialConfig config = 1;
   */
  config?: SerialConfig;
};

/**
 * Describes the message wave.v1.serial.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 7);

/**
 * @generated from message wave.v1.serial.CreateResponse
 */
export type CreateResponse = Message<"wave.v1.serial.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 8);

/**
 * @generated from message wave.v1.serial.UpdateRequest
 */
export type UpdateRequest = Message<"wave.v1.serial.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: wave.v1.serial.SerialConfig config = 2;
   */
  config?: SerialConfig;
};

/**
 * Describes the message wave.v1.serial.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 9);

/**
 * @generated from message wave.v1.serial.UpdateResponse
 */
export type UpdateResponse = Message<"wave.v1.serial.UpdateResponse"> & {
};

/**
 * Describes the message wave.v1.serial.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 10);

/**
 * @generated from message wave.v1.serial.DeleteRequest
 */
export type DeleteRequest = Message<"wave.v1.serial.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 11);

/**
 * @generated from message wave.v1.serial.DeleteResponse
 */
export type DeleteResponse = Message<"wave.v1.serial.DeleteResponse"> & {
};

/**
 * Describes the message wave.v1.serial.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 12);

