// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/serial/message.proto (package wave.v1.serial, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SerialConfig } from "./config_pb";
import { file_wave_v1_serial_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/serial/message.proto.
 */
export const file_wave_v1_serial_message: GenFile = /*@__PURE__*/
  fileDesc("Chx3YXZlL3YxL3NlcmlhbC9tZXNzYWdlLnByb3RvEg53YXZlLnYxLnNlcmlhbCJkCgZTZXJpYWwSDwoHcmVxbm9kZRgBIAEoCRIMCgRub2RlGAIgASgJEiwKBmNvbmZpZxgDIAEoCzIcLndhdmUudjEuc2VyaWFsLlNlcmlhbENvbmZpZxINCgVlcnJvchgIIAEoCSIYCgpHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIjUKC0dldFJlc3BvbnNlEiYKBnNlcmlhbBgBIAEoCzIWLndhdmUudjEuc2VyaWFsLlNlcmlhbCINCgtMaXN0UmVxdWVzdCI3CgxMaXN0UmVzcG9uc2USJwoHc2VyaWFscxgBIAMoCzIWLndhdmUudjEuc2VyaWFsLlNlcmlhbCI9Cg1DcmVhdGVSZXF1ZXN0EiwKBmNvbmZpZxgBIAEoCzIcLndhdmUudjEuc2VyaWFsLlNlcmlhbENvbmZpZyIcCg5DcmVhdGVSZXNwb25zZRIKCgJpZBgBIAEoCSJJCg1VcGRhdGVSZXF1ZXN0EgoKAmlkGAEgASgJEiwKBmNvbmZpZxgCIAEoCzIcLndhdmUudjEuc2VyaWFsLlNlcmlhbENvbmZpZyIQCg5VcGRhdGVSZXNwb25zZSIbCg1EZWxldGVSZXF1ZXN0EgoKAmlkGAEgASgJIhAKDkRlbGV0ZVJlc3BvbnNlQidaJWN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvd2F2ZS92MS9zZXJpYWxiBnByb3RvMw", [file_wave_v1_serial_config]);

/**
 * @generated from message wave.v1.serial.Serial
 */
export type Serial = Message<"wave.v1.serial.Serial"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * core prop
   *
   * @generated from field: wave.v1.serial.SerialConfig config = 3;
   */
  config?: SerialConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message wave.v1.serial.Serial.
 * Use `create(SerialSchema)` to create a new message.
 */
export const SerialSchema: GenMessage<Serial> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 0);

/**
 * @generated from message wave.v1.serial.GetRequest
 */
export type GetRequest = Message<"wave.v1.serial.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 1);

/**
 * @generated from message wave.v1.serial.GetResponse
 */
export type GetResponse = Message<"wave.v1.serial.GetResponse"> & {
  /**
   * @generated from field: wave.v1.serial.Serial serial = 1;
   */
  serial?: Serial;
};

/**
 * Describes the message wave.v1.serial.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 2);

/**
 * @generated from message wave.v1.serial.ListRequest
 */
export type ListRequest = Message<"wave.v1.serial.ListRequest"> & {
};

/**
 * Describes the message wave.v1.serial.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 3);

/**
 * @generated from message wave.v1.serial.ListResponse
 */
export type ListResponse = Message<"wave.v1.serial.ListResponse"> & {
  /**
   * @generated from field: repeated wave.v1.serial.Serial serials = 1;
   */
  serials: Serial[];
};

/**
 * Describes the message wave.v1.serial.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 4);

/**
 * @generated from message wave.v1.serial.CreateRequest
 */
export type CreateRequest = Message<"wave.v1.serial.CreateRequest"> & {
  /**
   * @generated from field: wave.v1.serial.SerialConfig config = 1;
   */
  config?: SerialConfig;
};

/**
 * Describes the message wave.v1.serial.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 5);

/**
 * @generated from message wave.v1.serial.CreateResponse
 */
export type CreateResponse = Message<"wave.v1.serial.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 6);

/**
 * @generated from message wave.v1.serial.UpdateRequest
 */
export type UpdateRequest = Message<"wave.v1.serial.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: wave.v1.serial.SerialConfig config = 2;
   */
  config?: SerialConfig;
};

/**
 * Describes the message wave.v1.serial.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 7);

/**
 * @generated from message wave.v1.serial.UpdateResponse
 */
export type UpdateResponse = Message<"wave.v1.serial.UpdateResponse"> & {
};

/**
 * Describes the message wave.v1.serial.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 8);

/**
 * @generated from message wave.v1.serial.DeleteRequest
 */
export type DeleteRequest = Message<"wave.v1.serial.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.serial.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 9);

/**
 * @generated from message wave.v1.serial.DeleteResponse
 */
export type DeleteResponse = Message<"wave.v1.serial.DeleteResponse"> & {
};

/**
 * Describes the message wave.v1.serial.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_serial_message, 10);

