// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/serial/service.proto (package wave.v1.serial, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { ConnectRequestSchema, ConnectResponseSchema, CreateRequestSchema, CreateResponseSchema, DeleteRequestSchema, DeleteResponseSchema, GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_wave_v1_serial_message } from "./message_pb";

/**
 * Describes the file wave/v1/serial/service.proto.
 */
export const file_wave_v1_serial_service: GenFile = /*@__PURE__*/
  fileDesc("Chx3YXZlL3YxL3NlcmlhbC9zZXJ2aWNlLnByb3RvEg53YXZlLnYxLnNlcmlhbDLJAwoNU2VyaWFsU2VydmljZRJACgNHZXQSGi53YXZlLnYxLnNlcmlhbC5HZXRSZXF1ZXN0Ghsud2F2ZS52MS5zZXJpYWwuR2V0UmVzcG9uc2UiABJQCgdDb25uZWN0Eh4ud2F2ZS52MS5zZXJpYWwuQ29ubmVjdFJlcXVlc3QaHy53YXZlLnYxLnNlcmlhbC5Db25uZWN0UmVzcG9uc2UiACgBMAESQwoETGlzdBIbLndhdmUudjEuc2VyaWFsLkxpc3RSZXF1ZXN0Ghwud2F2ZS52MS5zZXJpYWwuTGlzdFJlc3BvbnNlIgASSQoGQ3JlYXRlEh0ud2F2ZS52MS5zZXJpYWwuQ3JlYXRlUmVxdWVzdBoeLndhdmUudjEuc2VyaWFsLkNyZWF0ZVJlc3BvbnNlIgASSQoGVXBkYXRlEh0ud2F2ZS52MS5zZXJpYWwuVXBkYXRlUmVxdWVzdBoeLndhdmUudjEuc2VyaWFsLlVwZGF0ZVJlc3BvbnNlIgASSQoGRGVsZXRlEh0ud2F2ZS52MS5zZXJpYWwuRGVsZXRlUmVxdWVzdBoeLndhdmUudjEuc2VyaWFsLkRlbGV0ZVJlc3BvbnNlIgBCJ1olY3RodWwuaW8vY3RodWwvcGtnL2FwaS93YXZlL3YxL3NlcmlhbGIGcHJvdG8z", [file_wave_v1_serial_message]);

/**
 * @generated from service wave.v1.serial.SerialService
 */
export const SerialService: GenService<{
  /**
   * @generated from rpc wave.v1.serial.SerialService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.serial.SerialService.Connect
   */
  connect: {
    methodKind: "bidi_streaming";
    input: typeof ConnectRequestSchema;
    output: typeof ConnectResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.serial.SerialService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.serial.SerialService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateRequestSchema;
    output: typeof CreateResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.serial.SerialService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.serial.SerialService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wave_v1_serial_service, 0);

