// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: wave/v1/node/config.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_NODE_STATE_HEALTHY     NodeState = 0
	NodeState_NODE_STATE_DEGRADED    NodeState = 1
	NodeState_NODE_STATE_MAINTENANCE NodeState = 2
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_HEALTHY",
		1: "NODE_STATE_DEGRADED",
		2: "NODE_STATE_MAINTENANCE",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_HEALTHY":     0,
		"NODE_STATE_DEGRADED":    1,
		"NODE_STATE_MAINTENANCE": 2,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_wave_v1_node_config_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_wave_v1_node_config_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_wave_v1_node_config_proto_rawDescGZIP(), []int{0}
}

type NodeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affinity        []string  `protobuf:"bytes,1,rep,name=affinity,proto3" json:"affinity,omitempty"`
	State           NodeState `protobuf:"varint,2,opt,name=state,proto3,enum=wave.v1.node.NodeState" json:"state,omitempty"`
	AllocatedCpu    float64   `protobuf:"fixed64,3,opt,name=allocated_cpu,json=allocatedCpu,proto3" json:"allocated_cpu,omitempty"`
	AvailableCpu    float64   `protobuf:"fixed64,4,opt,name=available_cpu,json=availableCpu,proto3" json:"available_cpu,omitempty"`
	AllocatedMemory int64     `protobuf:"varint,5,opt,name=allocated_memory,json=allocatedMemory,proto3" json:"allocated_memory,omitempty"`
	AvailableMemory int64     `protobuf:"varint,6,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"`
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wave_v1_node_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wave_v1_node_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_wave_v1_node_config_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetAffinity() []string {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *NodeConfig) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_HEALTHY
}

func (x *NodeConfig) GetAllocatedCpu() float64 {
	if x != nil {
		return x.AllocatedCpu
	}
	return 0
}

func (x *NodeConfig) GetAvailableCpu() float64 {
	if x != nil {
		return x.AvailableCpu
	}
	return 0
}

func (x *NodeConfig) GetAllocatedMemory() int64 {
	if x != nil {
		return x.AllocatedMemory
	}
	return 0
}

func (x *NodeConfig) GetAvailableMemory() int64 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

var File_wave_v1_node_config_proto protoreflect.FileDescriptor

var file_wave_v1_node_config_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x61, 0x76, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x61, 0x76,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0xf7, 0x01, 0x0a, 0x0a, 0x4e, 0x6f,
	0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x66, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x63, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x43, 0x70, 0x75, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x70, 0x75, 0x12, 0x29, 0x0a,
	0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x2a, 0x58, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x48,
	0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x4f, 0x44, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x47, 0x52, 0x41, 0x44, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x42, 0x25, 0x5a,
	0x23, 0x63, 0x74, 0x68, 0x75, 0x6c, 0x2e, 0x69, 0x6f, 0x2f, 0x63, 0x74, 0x68, 0x75, 0x6c, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x61, 0x76, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wave_v1_node_config_proto_rawDescOnce sync.Once
	file_wave_v1_node_config_proto_rawDescData = file_wave_v1_node_config_proto_rawDesc
)

func file_wave_v1_node_config_proto_rawDescGZIP() []byte {
	file_wave_v1_node_config_proto_rawDescOnce.Do(func() {
		file_wave_v1_node_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_wave_v1_node_config_proto_rawDescData)
	})
	return file_wave_v1_node_config_proto_rawDescData
}

var file_wave_v1_node_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wave_v1_node_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wave_v1_node_config_proto_goTypes = []any{
	(NodeState)(0),     // 0: wave.v1.node.NodeState
	(*NodeConfig)(nil), // 1: wave.v1.node.NodeConfig
}
var file_wave_v1_node_config_proto_depIdxs = []int32{
	0, // 0: wave.v1.node.NodeConfig.state:type_name -> wave.v1.node.NodeState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wave_v1_node_config_proto_init() }
func file_wave_v1_node_config_proto_init() {
	if File_wave_v1_node_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wave_v1_node_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NodeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wave_v1_node_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wave_v1_node_config_proto_goTypes,
		DependencyIndexes: file_wave_v1_node_config_proto_depIdxs,
		EnumInfos:         file_wave_v1_node_config_proto_enumTypes,
		MessageInfos:      file_wave_v1_node_config_proto_msgTypes,
	}.Build()
	File_wave_v1_node_config_proto = out.File
	file_wave_v1_node_config_proto_rawDesc = nil
	file_wave_v1_node_config_proto_goTypes = nil
	file_wave_v1_node_config_proto_depIdxs = nil
}
