// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file granit/v1/disk/cluster.proto (package granit.v1.disk, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file granit/v1/disk/cluster.proto.
 */
export const file_granit_v1_disk_cluster: GenFile = /*@__PURE__*/
  fileDesc("ChxncmFuaXQvdjEvZGlzay9jbHVzdGVyLnByb3RvEg5ncmFuaXQudjEuZGlzayKOAQoLRGlza0NsdXN0ZXISNQoFbm9kZXMYASADKAsyJi5ncmFuaXQudjEuZGlzay5EaXNrQ2x1c3Rlci5Ob2Rlc0VudHJ5GkgKCk5vZGVzRW50cnkSCwoDa2V5GAEgASgJEikKBXZhbHVlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcDoCOAFCJ1olY3RodWwuaW8vY3RodWwvcGtnL2FwaS9ncmFuaXQvdjEvZGlza2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message granit.v1.disk.DiskCluster
 */
export type DiskCluster = Message<"granit.v1.disk.DiskCluster"> & {
  /**
   * @generated from field: map<string, google.protobuf.Timestamp> nodes = 1;
   */
  nodes: { [key: string]: Timestamp };
};

/**
 * Describes the message granit.v1.disk.DiskCluster.
 * Use `create(DiskClusterSchema)` to create a new message.
 */
export const DiskClusterSchema: GenMessage<DiskCluster> = /*@__PURE__*/
  messageDesc(file_granit_v1_disk_cluster, 0);

