// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file granit/v1/disk/service.proto (package granit.v1.disk, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CreateRequestSchema, CreateResponseSchema, DeleteRequestSchema, DeleteResponseSchema, GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_granit_v1_disk_message } from "./message_pb";

/**
 * Describes the file granit/v1/disk/service.proto.
 */
export const file_granit_v1_disk_service: GenFile = /*@__PURE__*/
  fileDesc("ChxncmFuaXQvdjEvZGlzay9zZXJ2aWNlLnByb3RvEg5ncmFuaXQudjEuZGlzazL1AgoLRGlza1NlcnZpY2USQAoDR2V0EhouZ3Jhbml0LnYxLmRpc2suR2V0UmVxdWVzdBobLmdyYW5pdC52MS5kaXNrLkdldFJlc3BvbnNlIgASQwoETGlzdBIbLmdyYW5pdC52MS5kaXNrLkxpc3RSZXF1ZXN0GhwuZ3Jhbml0LnYxLmRpc2suTGlzdFJlc3BvbnNlIgASSQoGQ3JlYXRlEh0uZ3Jhbml0LnYxLmRpc2suQ3JlYXRlUmVxdWVzdBoeLmdyYW5pdC52MS5kaXNrLkNyZWF0ZVJlc3BvbnNlIgASSQoGVXBkYXRlEh0uZ3Jhbml0LnYxLmRpc2suVXBkYXRlUmVxdWVzdBoeLmdyYW5pdC52MS5kaXNrLlVwZGF0ZVJlc3BvbnNlIgASSQoGRGVsZXRlEh0uZ3Jhbml0LnYxLmRpc2suRGVsZXRlUmVxdWVzdBoeLmdyYW5pdC52MS5kaXNrLkRlbGV0ZVJlc3BvbnNlIgBCJ1olY3RodWwuaW8vY3RodWwvcGtnL2FwaS9ncmFuaXQvdjEvZGlza2IGcHJvdG8z", [file_granit_v1_disk_message]);

/**
 * @generated from service granit.v1.disk.DiskService
 */
export const DiskService: GenService<{
  /**
   * @generated from rpc granit.v1.disk.DiskService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc granit.v1.disk.DiskService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc granit.v1.disk.DiskService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateRequestSchema;
    output: typeof CreateResponseSchema;
  },
  /**
   * @generated from rpc granit.v1.disk.DiskService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc granit.v1.disk.DiskService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_granit_v1_disk_service, 0);

