// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/node/service.proto (package wave.v1.node, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema } from "./message_pb";
import { file_wave_v1_node_message } from "./message_pb";

/**
 * Describes the file wave/v1/node/service.proto.
 */
export const file_wave_v1_node_service: GenFile = /*@__PURE__*/
  fileDesc("Chp3YXZlL3YxL25vZGUvc2VydmljZS5wcm90bxIMd2F2ZS52MS5ub2RlMowBCgtOb2RlU2VydmljZRI8CgNHZXQSGC53YXZlLnYxLm5vZGUuR2V0UmVxdWVzdBoZLndhdmUudjEubm9kZS5HZXRSZXNwb25zZSIAEj8KBExpc3QSGS53YXZlLnYxLm5vZGUuTGlzdFJlcXVlc3QaGi53YXZlLnYxLm5vZGUuTGlzdFJlc3BvbnNlIgBCJVojY3RodWwuaW8vY3RodWwvcGtnL2FwaS93YXZlL3YxL25vZGViBnByb3RvMw", [file_wave_v1_node_message]);

/**
 * @generated from service wave.v1.node.NodeService
 */
export const NodeService: GenService<{
  /**
   * @generated from rpc wave.v1.node.NodeService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.node.NodeService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wave_v1_node_service, 0);

