// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file rune/v1/message.proto (package rune.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rune/v1/message.proto.
 */
export const file_rune_v1_message: GenFile = /*@__PURE__*/
  fileDesc("ChVydW5lL3YxL21lc3NhZ2UucHJvdG8SB3J1bmUudjEiIwoVR2V0Q2VydGlmaWNhdGVSZXF1ZXN0EgoKAmlkGAEgASgDIiQKFkdldENlcnRpZmljYXRlUmVzcG9uc2USCgoCaWQYASABKANCJ1olY3RodWwuaW8vY3RodWwvcGtnL2FwaS9ydW5lL3YxO3J1bmV2MWIGcHJvdG8z");

/**
 * @generated from message rune.v1.GetCertificateRequest
 */
export type GetCertificateRequest = Message<"rune.v1.GetCertificateRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message rune.v1.GetCertificateRequest.
 * Use `create(GetCertificateRequestSchema)` to create a new message.
 */
export const GetCertificateRequestSchema: GenMessage<GetCertificateRequest> = /*@__PURE__*/
  messageDesc(file_rune_v1_message, 0);

/**
 * @generated from message rune.v1.GetCertificateResponse
 */
export type GetCertificateResponse = Message<"rune.v1.GetCertificateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message rune.v1.GetCertificateResponse.
 * Use `create(GetCertificateResponseSchema)` to create a new message.
 */
export const GetCertificateResponseSchema: GenMessage<GetCertificateResponse> = /*@__PURE__*/
  messageDesc(file_rune_v1_message, 1);

