// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file rune/v1/service.proto (package rune.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { GetCertificateRequestSchema, GetCertificateResponseSchema } from "./message_pb";
import { file_rune_v1_message } from "./message_pb";

/**
 * Describes the file rune/v1/service.proto.
 */
export const file_rune_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChVydW5lL3YxL3NlcnZpY2UucHJvdG8SB3J1bmUudjEyaQoSQ2VydGlmaWNhdGVTZXJ2aWNlElMKDkdldENlcnRpZmljYXRlEh4ucnVuZS52MS5HZXRDZXJ0aWZpY2F0ZVJlcXVlc3QaHy5ydW5lLnYxLkdldENlcnRpZmljYXRlUmVzcG9uc2UiAEInWiVjdGh1bC5pby9jdGh1bC9wa2cvYXBpL3J1bmUvdjE7cnVuZXYxYgZwcm90bzM", [file_rune_v1_message]);

/**
 * @generated from service rune.v1.CertificateService
 */
export const CertificateService: GenService<{
  /**
   * @generated from rpc rune.v1.CertificateService.GetCertificate
   */
  getCertificate: {
    methodKind: "unary";
    input: typeof GetCertificateRequestSchema;
    output: typeof GetCertificateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_rune_v1_service, 0);

