// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/video/message.proto (package wave.v1.video, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { VideoConfig } from "./config_pb";
import { file_wave_v1_video_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/video/message.proto.
 */
export const file_wave_v1_video_message: GenFile = /*@__PURE__*/
  fileDesc("Cht3YXZlL3YxL3ZpZGVvL21lc3NhZ2UucHJvdG8SDXdhdmUudjEudmlkZW8iYQoFVmlkZW8SDwoHcmVxbm9kZRgBIAEoCRIMCgRub2RlGAIgASgJEioKBmNvbmZpZxgDIAEoCzIaLndhdmUudjEudmlkZW8uVmlkZW9Db25maWcSDQoFZXJyb3IYCCABKAkiGAoKR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSIyCgtHZXRSZXNwb25zZRIjCgV2aWRlbxgBIAEoCzIULndhdmUudjEudmlkZW8uVmlkZW8iHwoOQ29ubmVjdFJlcXVlc3QSDQoFaW5wdXQYASABKAwiIQoPQ29ubmVjdFJlc3BvbnNlEg4KBm91dHB1dBgBIAEoDCINCgtMaXN0UmVxdWVzdCKMAQoMTGlzdFJlc3BvbnNlEjcKBnZpZGVvcxgBIAMoCzInLndhdmUudjEudmlkZW8uTGlzdFJlc3BvbnNlLlZpZGVvc0VudHJ5GkMKC1ZpZGVvc0VudHJ5EgsKA2tleRgBIAEoCRIjCgV2YWx1ZRgCIAEoCzIULndhdmUudjEudmlkZW8uVmlkZW86AjgBIjsKDUNyZWF0ZVJlcXVlc3QSKgoGY29uZmlnGAEgASgLMhoud2F2ZS52MS52aWRlby5WaWRlb0NvbmZpZyIcCg5DcmVhdGVSZXNwb25zZRIKCgJpZBgBIAEoCSJHCg1VcGRhdGVSZXF1ZXN0EgoKAmlkGAEgASgJEioKBmNvbmZpZxgCIAEoCzIaLndhdmUudjEudmlkZW8uVmlkZW9Db25maWciEAoOVXBkYXRlUmVzcG9uc2UiGwoNRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCSIQCg5EZWxldGVSZXNwb25zZUImWiRjdGh1bC5pby9jdGh1bC9wa2cvYXBpL3dhdmUvdjEvdmlkZW9iBnByb3RvMw", [file_wave_v1_video_config]);

/**
 * @generated from message wave.v1.video.Video
 */
export type Video = Message<"wave.v1.video.Video"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * core prop
   *
   * @generated from field: wave.v1.video.VideoConfig config = 3;
   */
  config?: VideoConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message wave.v1.video.Video.
 * Use `create(VideoSchema)` to create a new message.
 */
export const VideoSchema: GenMessage<Video> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 0);

/**
 * @generated from message wave.v1.video.GetRequest
 */
export type GetRequest = Message<"wave.v1.video.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.video.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 1);

/**
 * @generated from message wave.v1.video.GetResponse
 */
export type GetResponse = Message<"wave.v1.video.GetResponse"> & {
  /**
   * @generated from field: wave.v1.video.Video video = 1;
   */
  video?: Video;
};

/**
 * Describes the message wave.v1.video.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 2);

/**
 * @generated from message wave.v1.video.ConnectRequest
 */
export type ConnectRequest = Message<"wave.v1.video.ConnectRequest"> & {
  /**
   * @generated from field: bytes input = 1;
   */
  input: Uint8Array;
};

/**
 * Describes the message wave.v1.video.ConnectRequest.
 * Use `create(ConnectRequestSchema)` to create a new message.
 */
export const ConnectRequestSchema: GenMessage<ConnectRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 3);

/**
 * @generated from message wave.v1.video.ConnectResponse
 */
export type ConnectResponse = Message<"wave.v1.video.ConnectResponse"> & {
  /**
   * @generated from field: bytes output = 1;
   */
  output: Uint8Array;
};

/**
 * Describes the message wave.v1.video.ConnectResponse.
 * Use `create(ConnectResponseSchema)` to create a new message.
 */
export const ConnectResponseSchema: GenMessage<ConnectResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 4);

/**
 * @generated from message wave.v1.video.ListRequest
 */
export type ListRequest = Message<"wave.v1.video.ListRequest"> & {
};

/**
 * Describes the message wave.v1.video.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 5);

/**
 * @generated from message wave.v1.video.ListResponse
 */
export type ListResponse = Message<"wave.v1.video.ListResponse"> & {
  /**
   * @generated from field: map<string, wave.v1.video.Video> videos = 1;
   */
  videos: { [key: string]: Video };
};

/**
 * Describes the message wave.v1.video.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 6);

/**
 * @generated from message wave.v1.video.CreateRequest
 */
export type CreateRequest = Message<"wave.v1.video.CreateRequest"> & {
  /**
   * @generated from field: wave.v1.video.VideoConfig config = 1;
   */
  config?: VideoConfig;
};

/**
 * Describes the message wave.v1.video.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 7);

/**
 * @generated from message wave.v1.video.CreateResponse
 */
export type CreateResponse = Message<"wave.v1.video.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.video.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 8);

/**
 * @generated from message wave.v1.video.UpdateRequest
 */
export type UpdateRequest = Message<"wave.v1.video.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: wave.v1.video.VideoConfig config = 2;
   */
  config?: VideoConfig;
};

/**
 * Describes the message wave.v1.video.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 9);

/**
 * @generated from message wave.v1.video.UpdateResponse
 */
export type UpdateResponse = Message<"wave.v1.video.UpdateResponse"> & {
};

/**
 * Describes the message wave.v1.video.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 10);

/**
 * @generated from message wave.v1.video.DeleteRequest
 */
export type DeleteRequest = Message<"wave.v1.video.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.video.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 11);

/**
 * @generated from message wave.v1.video.DeleteResponse
 */
export type DeleteResponse = Message<"wave.v1.video.DeleteResponse"> & {
};

/**
 * Describes the message wave.v1.video.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_video_message, 12);

