// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/video/service.proto (package wave.v1.video, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CreateRequestSchema, CreateResponseSchema, DeleteRequestSchema, DeleteResponseSchema, GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_wave_v1_video_message } from "./message_pb";

/**
 * Describes the file wave/v1/video/service.proto.
 */
export const file_wave_v1_video_service: GenFile = /*@__PURE__*/
  fileDesc("Cht3YXZlL3YxL3ZpZGVvL3NlcnZpY2UucHJvdG8SDXdhdmUudjEudmlkZW8y7AIKDFZpZGVvU2VydmljZRI+CgNHZXQSGS53YXZlLnYxLnZpZGVvLkdldFJlcXVlc3QaGi53YXZlLnYxLnZpZGVvLkdldFJlc3BvbnNlIgASQQoETGlzdBIaLndhdmUudjEudmlkZW8uTGlzdFJlcXVlc3QaGy53YXZlLnYxLnZpZGVvLkxpc3RSZXNwb25zZSIAEkcKBkNyZWF0ZRIcLndhdmUudjEudmlkZW8uQ3JlYXRlUmVxdWVzdBodLndhdmUudjEudmlkZW8uQ3JlYXRlUmVzcG9uc2UiABJHCgZVcGRhdGUSHC53YXZlLnYxLnZpZGVvLlVwZGF0ZVJlcXVlc3QaHS53YXZlLnYxLnZpZGVvLlVwZGF0ZVJlc3BvbnNlIgASRwoGRGVsZXRlEhwud2F2ZS52MS52aWRlby5EZWxldGVSZXF1ZXN0Gh0ud2F2ZS52MS52aWRlby5EZWxldGVSZXNwb25zZSIAQiZaJGN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvd2F2ZS92MS92aWRlb2IGcHJvdG8z", [file_wave_v1_video_message]);

/**
 * @generated from service wave.v1.video.VideoService
 */
export const VideoService: GenService<{
  /**
   * @generated from rpc wave.v1.video.VideoService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.video.VideoService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.video.VideoService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateRequestSchema;
    output: typeof CreateResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.video.VideoService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc wave.v1.video.VideoService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wave_v1_video_service, 0);

