// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file proton/v1/inter/cluster.proto (package proton.v1.inter, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proton/v1/inter/cluster.proto.
 */
export const file_proton_v1_inter_cluster: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90b24vdjEvaW50ZXIvY2x1c3Rlci5wcm90bxIPcHJvdG9uLnYxLmludGVyIpEBCgxJbnRlckNsdXN0ZXISNwoFbm9kZXMYASADKAsyKC5wcm90b24udjEuaW50ZXIuSW50ZXJDbHVzdGVyLk5vZGVzRW50cnkaSAoKTm9kZXNFbnRyeRILCgNrZXkYASABKAkSKQoFdmFsdWUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wOgI4AUIoWiZjdGh1bC5pby9jdGh1bC9wa2cvYXBpL3Byb3Rvbi92MS9pbnRlcmIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message proton.v1.inter.InterCluster
 */
export type InterCluster = Message<"proton.v1.inter.InterCluster"> & {
  /**
   * @generated from field: map<string, google.protobuf.Timestamp> nodes = 1;
   */
  nodes: { [key: string]: Timestamp };
};

/**
 * Describes the message proton.v1.inter.InterCluster.
 * Use `create(InterClusterSchema)` to create a new message.
 */
export const InterClusterSchema: GenMessage<InterCluster> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_cluster, 0);

