// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file proton/v1/inter/config.proto (package proton.v1.inter, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proton/v1/inter/config.proto.
 */
export const file_proton_v1_inter_config: GenFile = /*@__PURE__*/
  fileDesc("Chxwcm90b24vdjEvaW50ZXIvY29uZmlnLnByb3RvEg9wcm90b24udjEuaW50ZXIiHQoLSW50ZXJDb25maWcSDgoGZGV2aWNlGAEgASgJQihaJmN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvcHJvdG9uL3YxL2ludGVyYgZwcm90bzM");

/**
 * @generated from message proton.v1.inter.InterConfig
 */
export type InterConfig = Message<"proton.v1.inter.InterConfig"> & {
  /**
   * @generated from field: string device = 1;
   */
  device: string;
};

/**
 * Describes the message proton.v1.inter.InterConfig.
 * Use `create(InterConfigSchema)` to create a new message.
 */
export const InterConfigSchema: GenMessage<InterConfig> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_config, 0);

