// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file proton/v1/inter/service.proto (package proton.v1.inter, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CreateRequestSchema, CreateResponseSchema, DeleteRequestSchema, DeleteResponseSchema, GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_proton_v1_inter_message } from "./message_pb";

/**
 * Describes the file proton/v1/inter/service.proto.
 */
export const file_proton_v1_inter_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90b24vdjEvaW50ZXIvc2VydmljZS5wcm90bxIPcHJvdG9uLnYxLmludGVyMoADCgxJbnRlclNlcnZpY2USQgoDR2V0EhsucHJvdG9uLnYxLmludGVyLkdldFJlcXVlc3QaHC5wcm90b24udjEuaW50ZXIuR2V0UmVzcG9uc2UiABJFCgRMaXN0EhwucHJvdG9uLnYxLmludGVyLkxpc3RSZXF1ZXN0Gh0ucHJvdG9uLnYxLmludGVyLkxpc3RSZXNwb25zZSIAEksKBkNyZWF0ZRIeLnByb3Rvbi52MS5pbnRlci5DcmVhdGVSZXF1ZXN0Gh8ucHJvdG9uLnYxLmludGVyLkNyZWF0ZVJlc3BvbnNlIgASSwoGVXBkYXRlEh4ucHJvdG9uLnYxLmludGVyLlVwZGF0ZVJlcXVlc3QaHy5wcm90b24udjEuaW50ZXIuVXBkYXRlUmVzcG9uc2UiABJLCgZEZWxldGUSHi5wcm90b24udjEuaW50ZXIuRGVsZXRlUmVxdWVzdBofLnByb3Rvbi52MS5pbnRlci5EZWxldGVSZXNwb25zZSIAQihaJmN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvcHJvdG9uL3YxL2ludGVyYgZwcm90bzM", [file_proton_v1_inter_message]);

/**
 * @generated from service proton.v1.inter.InterService
 */
export const InterService: GenService<{
  /**
   * @generated from rpc proton.v1.inter.InterService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc proton.v1.inter.InterService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc proton.v1.inter.InterService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateRequestSchema;
    output: typeof CreateResponseSchema;
  },
  /**
   * @generated from rpc proton.v1.inter.InterService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc proton.v1.inter.InterService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proton_v1_inter_service, 0);

