// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proton/v1/inter/cluster.proto

package inter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes map[string]*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InterCluster) Reset() {
	*x = InterCluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proton_v1_inter_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterCluster) ProtoMessage() {}

func (x *InterCluster) ProtoReflect() protoreflect.Message {
	mi := &file_proton_v1_inter_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterCluster.ProtoReflect.Descriptor instead.
func (*InterCluster) Descriptor() ([]byte, []int) {
	return file_proton_v1_inter_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *InterCluster) GetNodes() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_proton_v1_inter_cluster_proto protoreflect.FileDescriptor

var file_proton_v1_inter_cluster_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x3e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x1a, 0x54, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x63, 0x74, 0x68, 0x75,
	0x6c, 0x2e, 0x69, 0x6f, 0x2f, 0x63, 0x74, 0x68, 0x75, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proton_v1_inter_cluster_proto_rawDescOnce sync.Once
	file_proton_v1_inter_cluster_proto_rawDescData = file_proton_v1_inter_cluster_proto_rawDesc
)

func file_proton_v1_inter_cluster_proto_rawDescGZIP() []byte {
	file_proton_v1_inter_cluster_proto_rawDescOnce.Do(func() {
		file_proton_v1_inter_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_proton_v1_inter_cluster_proto_rawDescData)
	})
	return file_proton_v1_inter_cluster_proto_rawDescData
}

var file_proton_v1_inter_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proton_v1_inter_cluster_proto_goTypes = []any{
	(*InterCluster)(nil),          // 0: proton.v1.inter.InterCluster
	nil,                           // 1: proton.v1.inter.InterCluster.NodesEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proton_v1_inter_cluster_proto_depIdxs = []int32{
	1, // 0: proton.v1.inter.InterCluster.nodes:type_name -> proton.v1.inter.InterCluster.NodesEntry
	2, // 1: proton.v1.inter.InterCluster.NodesEntry.value:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proton_v1_inter_cluster_proto_init() }
func file_proton_v1_inter_cluster_proto_init() {
	if File_proton_v1_inter_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proton_v1_inter_cluster_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InterCluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proton_v1_inter_cluster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proton_v1_inter_cluster_proto_goTypes,
		DependencyIndexes: file_proton_v1_inter_cluster_proto_depIdxs,
		MessageInfos:      file_proton_v1_inter_cluster_proto_msgTypes,
	}.Build()
	File_proton_v1_inter_cluster_proto = out.File
	file_proton_v1_inter_cluster_proto_rawDesc = nil
	file_proton_v1_inter_cluster_proto_goTypes = nil
	file_proton_v1_inter_cluster_proto_depIdxs = nil
}
