// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/node/config.proto (package wave.v1.node, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/node/config.proto.
 */
export const file_wave_v1_node_config: GenFile = /*@__PURE__*/
  fileDesc("Chl3YXZlL3YxL25vZGUvY29uZmlnLnByb3RvEgx3YXZlLnYxLm5vZGUiqAEKCk5vZGVDb25maWcSEAoIYWZmaW5pdHkYASADKAkSJgoFc3RhdGUYAiABKA4yFy53YXZlLnYxLm5vZGUuTm9kZVN0YXRlEhUKDWFsbG9jYXRlZF9jcHUYAyABKAESFQoNYXZhaWxhYmxlX2NwdRgEIAEoARIYChBhbGxvY2F0ZWRfbWVtb3J5GAUgASgDEhgKEGF2YWlsYWJsZV9tZW1vcnkYBiABKAMqWAoJTm9kZVN0YXRlEhYKEk5PREVfU1RBVEVfSEVBTFRIWRAAEhcKE05PREVfU1RBVEVfREVHUkFERUQQARIaChZOT0RFX1NUQVRFX01BSU5URU5BTkNFEAJCJVojY3RodWwuaW8vY3RodWwvcGtnL2FwaS93YXZlL3YxL25vZGViBnByb3RvMw");

/**
 * @generated from message wave.v1.node.NodeConfig
 */
export type NodeConfig = Message<"wave.v1.node.NodeConfig"> & {
  /**
   * @generated from field: repeated string affinity = 1;
   */
  affinity: string[];

  /**
   * @generated from field: wave.v1.node.NodeState state = 2;
   */
  state: NodeState;

  /**
   * @generated from field: double allocated_cpu = 3;
   */
  allocatedCpu: number;

  /**
   * @generated from field: double available_cpu = 4;
   */
  availableCpu: number;

  /**
   * @generated from field: int64 allocated_memory = 5;
   */
  allocatedMemory: bigint;

  /**
   * @generated from field: int64 available_memory = 6;
   */
  availableMemory: bigint;
};

/**
 * Describes the message wave.v1.node.NodeConfig.
 * Use `create(NodeConfigSchema)` to create a new message.
 */
export const NodeConfigSchema: GenMessage<NodeConfig> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_config, 0);

/**
 * @generated from enum wave.v1.node.NodeState
 */
export enum NodeState {
  /**
   * @generated from enum value: NODE_STATE_HEALTHY = 0;
   */
  HEALTHY = 0,

  /**
   * @generated from enum value: NODE_STATE_DEGRADED = 1;
   */
  DEGRADED = 1,

  /**
   * @generated from enum value: NODE_STATE_MAINTENANCE = 2;
   */
  MAINTENANCE = 2,
}

/**
 * Describes the enum wave.v1.node.NodeState.
 */
export const NodeStateSchema: GenEnum<NodeState> = /*@__PURE__*/
  enumDesc(file_wave_v1_node_config, 0);

