// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/node/message.proto (package wave.v1.node, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { NodeConfig } from "./config_pb";
import { file_wave_v1_node_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/node/message.proto.
 */
export const file_wave_v1_node_message: GenFile = /*@__PURE__*/
  fileDesc("Chp3YXZlL3YxL25vZGUvbWVzc2FnZS5wcm90bxIMd2F2ZS52MS5ub2RlIj8KBE5vZGUSKAoGY29uZmlnGAUgASgLMhgud2F2ZS52MS5ub2RlLk5vZGVDb25maWcSDQoFZXJyb3IYBiABKAkiGAoKR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSIvCgtHZXRSZXNwb25zZRIgCgRub2RlGAEgASgLMhIud2F2ZS52MS5ub2RlLk5vZGUiDQoLTGlzdFJlcXVlc3QihgEKDExpc3RSZXNwb25zZRI0CgVub2RlcxgBIAMoCzIlLndhdmUudjEubm9kZS5MaXN0UmVzcG9uc2UuTm9kZXNFbnRyeRpACgpOb2Rlc0VudHJ5EgsKA2tleRgBIAEoCRIhCgV2YWx1ZRgCIAEoCzISLndhdmUudjEubm9kZS5Ob2RlOgI4AUIlWiNjdGh1bC5pby9jdGh1bC9wa2cvYXBpL3dhdmUvdjEvbm9kZWIGcHJvdG8z", [file_wave_v1_node_config]);

/**
 * @generated from message wave.v1.node.Node
 */
export type Node = Message<"wave.v1.node.Node"> & {
  /**
   * @generated from field: wave.v1.node.NodeConfig config = 5;
   */
  config?: NodeConfig;

  /**
   * @generated from field: string error = 6;
   */
  error: string;
};

/**
 * Describes the message wave.v1.node.Node.
 * Use `create(NodeSchema)` to create a new message.
 */
export const NodeSchema: GenMessage<Node> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_message, 0);

/**
 * @generated from message wave.v1.node.GetRequest
 */
export type GetRequest = Message<"wave.v1.node.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.node.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_message, 1);

/**
 * @generated from message wave.v1.node.GetResponse
 */
export type GetResponse = Message<"wave.v1.node.GetResponse"> & {
  /**
   * @generated from field: wave.v1.node.Node node = 1;
   */
  node?: Node;
};

/**
 * Describes the message wave.v1.node.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_message, 2);

/**
 * @generated from message wave.v1.node.ListRequest
 */
export type ListRequest = Message<"wave.v1.node.ListRequest"> & {
};

/**
 * Describes the message wave.v1.node.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_message, 3);

/**
 * @generated from message wave.v1.node.ListResponse
 */
export type ListResponse = Message<"wave.v1.node.ListResponse"> & {
  /**
   * @generated from field: map<string, wave.v1.node.Node> nodes = 1;
   */
  nodes: { [key: string]: Node };
};

/**
 * Describes the message wave.v1.node.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_node_message, 4);

