// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file wave/v1/domain/message.proto (package wave.v1.domain, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { DomainConfig } from "./config_pb";
import { file_wave_v1_domain_config } from "./config_pb";
import type { DomainStats } from "./stat_pb";
import { file_wave_v1_domain_stat } from "./stat_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wave/v1/domain/message.proto.
 */
export const file_wave_v1_domain_message: GenFile = /*@__PURE__*/
  fileDesc("Chx3YXZlL3YxL2RvbWFpbi9tZXNzYWdlLnByb3RvEg53YXZlLnYxLmRvbWFpbiJkCgZEb21haW4SDwoHcmVxbm9kZRgBIAEoCRIMCgRub2RlGAIgASgJEiwKBmNvbmZpZxgDIAEoCzIcLndhdmUudjEuZG9tYWluLkRvbWFpbkNvbmZpZxINCgVlcnJvchgIIAEoCSIYCgpHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIjUKC0dldFJlc3BvbnNlEiYKBmRvbWFpbhgBIAEoCzIWLndhdmUudjEuZG9tYWluLkRvbWFpbiIZCgtTdGF0UmVxdWVzdBIKCgJpZBgBIAEoCSI6CgxTdGF0UmVzcG9uc2USKgoFc3RhdHMYASABKAsyGy53YXZlLnYxLmRvbWFpbi5Eb21haW5TdGF0cyINCgtMaXN0UmVxdWVzdCKSAQoMTGlzdFJlc3BvbnNlEjoKB2RvbWFpbnMYASADKAsyKS53YXZlLnYxLmRvbWFpbi5MaXN0UmVzcG9uc2UuRG9tYWluc0VudHJ5GkYKDERvbWFpbnNFbnRyeRILCgNrZXkYASABKAkSJQoFdmFsdWUYAiABKAsyFi53YXZlLnYxLmRvbWFpbi5Eb21haW46AjgBIj0KDUNyZWF0ZVJlcXVlc3QSLAoGY29uZmlnGAEgASgLMhwud2F2ZS52MS5kb21haW4uRG9tYWluQ29uZmlnIhwKDkNyZWF0ZVJlc3BvbnNlEgoKAmlkGAEgASgJIkkKDVVwZGF0ZVJlcXVlc3QSCgoCaWQYASABKAkSLAoGY29uZmlnGAIgASgLMhwud2F2ZS52MS5kb21haW4uRG9tYWluQ29uZmlnIhAKDlVwZGF0ZVJlc3BvbnNlIikKDUF0dGFjaFJlcXVlc3QSCgoCaWQYASABKAkSDAoEbm9kZRgCIAEoCSIQCg5BdHRhY2hSZXNwb25zZSIbCg1EZXRhY2hSZXF1ZXN0EgoKAmlkGAEgASgJIhAKDkRldGFjaFJlc3BvbnNlIhsKDURlbGV0ZVJlcXVlc3QSCgoCaWQYASABKAkiEAoORGVsZXRlUmVzcG9uc2VCJ1olY3RodWwuaW8vY3RodWwvcGtnL2FwaS93YXZlL3YxL2RvbWFpbmIGcHJvdG8z", [file_wave_v1_domain_config, file_wave_v1_domain_stat]);

/**
 * @generated from message wave.v1.domain.Domain
 */
export type Domain = Message<"wave.v1.domain.Domain"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * core prop
   *
   * @generated from field: wave.v1.domain.DomainConfig config = 3;
   */
  config?: DomainConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message wave.v1.domain.Domain.
 * Use `create(DomainSchema)` to create a new message.
 */
export const DomainSchema: GenMessage<Domain> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 0);

/**
 * @generated from message wave.v1.domain.GetRequest
 */
export type GetRequest = Message<"wave.v1.domain.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.domain.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 1);

/**
 * @generated from message wave.v1.domain.GetResponse
 */
export type GetResponse = Message<"wave.v1.domain.GetResponse"> & {
  /**
   * @generated from field: wave.v1.domain.Domain domain = 1;
   */
  domain?: Domain;
};

/**
 * Describes the message wave.v1.domain.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 2);

/**
 * @generated from message wave.v1.domain.StatRequest
 */
export type StatRequest = Message<"wave.v1.domain.StatRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.domain.StatRequest.
 * Use `create(StatRequestSchema)` to create a new message.
 */
export const StatRequestSchema: GenMessage<StatRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 3);

/**
 * @generated from message wave.v1.domain.StatResponse
 */
export type StatResponse = Message<"wave.v1.domain.StatResponse"> & {
  /**
   * @generated from field: wave.v1.domain.DomainStats stats = 1;
   */
  stats?: DomainStats;
};

/**
 * Describes the message wave.v1.domain.StatResponse.
 * Use `create(StatResponseSchema)` to create a new message.
 */
export const StatResponseSchema: GenMessage<StatResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 4);

/**
 * @generated from message wave.v1.domain.ListRequest
 */
export type ListRequest = Message<"wave.v1.domain.ListRequest"> & {
};

/**
 * Describes the message wave.v1.domain.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 5);

/**
 * @generated from message wave.v1.domain.ListResponse
 */
export type ListResponse = Message<"wave.v1.domain.ListResponse"> & {
  /**
   * @generated from field: map<string, wave.v1.domain.Domain> domains = 1;
   */
  domains: { [key: string]: Domain };
};

/**
 * Describes the message wave.v1.domain.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 6);

/**
 * @generated from message wave.v1.domain.CreateRequest
 */
export type CreateRequest = Message<"wave.v1.domain.CreateRequest"> & {
  /**
   * @generated from field: wave.v1.domain.DomainConfig config = 1;
   */
  config?: DomainConfig;
};

/**
 * Describes the message wave.v1.domain.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 7);

/**
 * @generated from message wave.v1.domain.CreateResponse
 */
export type CreateResponse = Message<"wave.v1.domain.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.domain.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 8);

/**
 * @generated from message wave.v1.domain.UpdateRequest
 */
export type UpdateRequest = Message<"wave.v1.domain.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: wave.v1.domain.DomainConfig config = 2;
   */
  config?: DomainConfig;
};

/**
 * Describes the message wave.v1.domain.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 9);

/**
 * @generated from message wave.v1.domain.UpdateResponse
 */
export type UpdateResponse = Message<"wave.v1.domain.UpdateResponse"> & {
};

/**
 * Describes the message wave.v1.domain.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 10);

/**
 * @generated from message wave.v1.domain.AttachRequest
 */
export type AttachRequest = Message<"wave.v1.domain.AttachRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;
};

/**
 * Describes the message wave.v1.domain.AttachRequest.
 * Use `create(AttachRequestSchema)` to create a new message.
 */
export const AttachRequestSchema: GenMessage<AttachRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 11);

/**
 * @generated from message wave.v1.domain.AttachResponse
 */
export type AttachResponse = Message<"wave.v1.domain.AttachResponse"> & {
};

/**
 * Describes the message wave.v1.domain.AttachResponse.
 * Use `create(AttachResponseSchema)` to create a new message.
 */
export const AttachResponseSchema: GenMessage<AttachResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 12);

/**
 * @generated from message wave.v1.domain.DetachRequest
 */
export type DetachRequest = Message<"wave.v1.domain.DetachRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.domain.DetachRequest.
 * Use `create(DetachRequestSchema)` to create a new message.
 */
export const DetachRequestSchema: GenMessage<DetachRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 13);

/**
 * @generated from message wave.v1.domain.DetachResponse
 */
export type DetachResponse = Message<"wave.v1.domain.DetachResponse"> & {
};

/**
 * Describes the message wave.v1.domain.DetachResponse.
 * Use `create(DetachResponseSchema)` to create a new message.
 */
export const DetachResponseSchema: GenMessage<DetachResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 14);

/**
 * @generated from message wave.v1.domain.DeleteRequest
 */
export type DeleteRequest = Message<"wave.v1.domain.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message wave.v1.domain.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 15);

/**
 * @generated from message wave.v1.domain.DeleteResponse
 */
export type DeleteResponse = Message<"wave.v1.domain.DeleteResponse"> & {
};

/**
 * Describes the message wave.v1.domain.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_wave_v1_domain_message, 16);

