// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file proton/v1/inter/message.proto (package proton.v1.inter, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { InterConfig } from "./config_pb";
import { file_proton_v1_inter_config } from "./config_pb";
import type { InterCluster } from "./cluster_pb";
import { file_proton_v1_inter_cluster } from "./cluster_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proton/v1/inter/message.proto.
 */
export const file_proton_v1_inter_message: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90b24vdjEvaW50ZXIvbWVzc2FnZS5wcm90bxIPcHJvdG9uLnYxLmludGVyIpMBCgVJbnRlchIPCgdyZXFub2RlGAEgASgJEgwKBG5vZGUYAiABKAkSLgoHY2x1c3RlchgDIAEoCzIdLnByb3Rvbi52MS5pbnRlci5JbnRlckNsdXN0ZXISLAoGY29uZmlnGAQgASgLMhwucHJvdG9uLnYxLmludGVyLkludGVyQ29uZmlnEg0KBWVycm9yGAggASgJIhgKCkdldFJlcXVlc3QSCgoCaWQYASABKAkiNAoLR2V0UmVzcG9uc2USJQoFaW50ZXIYASABKAsyFi5wcm90b24udjEuaW50ZXIuSW50ZXIiDQoLTGlzdFJlcXVlc3QiNgoMTGlzdFJlc3BvbnNlEiYKBmludGVycxgBIAMoCzIWLnByb3Rvbi52MS5pbnRlci5JbnRlciI9Cg1DcmVhdGVSZXF1ZXN0EiwKBmNvbmZpZxgBIAEoCzIcLnByb3Rvbi52MS5pbnRlci5JbnRlckNvbmZpZyIcCg5DcmVhdGVSZXNwb25zZRIKCgJpZBgBIAEoCSJJCg1VcGRhdGVSZXF1ZXN0EgoKAmlkGAEgASgJEiwKBmNvbmZpZxgCIAEoCzIcLnByb3Rvbi52MS5pbnRlci5JbnRlckNvbmZpZyIQCg5VcGRhdGVSZXNwb25zZSIbCg1EZWxldGVSZXF1ZXN0EgoKAmlkGAEgASgJIhAKDkRlbGV0ZVJlc3BvbnNlQihaJmN0aHVsLmlvL2N0aHVsL3BrZy9hcGkvcHJvdG9uL3YxL2ludGVyYgZwcm90bzM", [file_proton_v1_inter_config, file_proton_v1_inter_cluster]);

/**
 * @generated from message proton.v1.inter.Inter
 */
export type Inter = Message<"proton.v1.inter.Inter"> & {
  /**
   * @generated from field: string reqnode = 1;
   */
  reqnode: string;

  /**
   * @generated from field: string node = 2;
   */
  node: string;

  /**
   * @generated from field: proton.v1.inter.InterCluster cluster = 3;
   */
  cluster?: InterCluster;

  /**
   * core prop
   *
   * @generated from field: proton.v1.inter.InterConfig config = 4;
   */
  config?: InterConfig;

  /**
   * @generated from field: string error = 8;
   */
  error: string;
};

/**
 * Describes the message proton.v1.inter.Inter.
 * Use `create(InterSchema)` to create a new message.
 */
export const InterSchema: GenMessage<Inter> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 0);

/**
 * @generated from message proton.v1.inter.GetRequest
 */
export type GetRequest = Message<"proton.v1.inter.GetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proton.v1.inter.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 1);

/**
 * @generated from message proton.v1.inter.GetResponse
 */
export type GetResponse = Message<"proton.v1.inter.GetResponse"> & {
  /**
   * @generated from field: proton.v1.inter.Inter inter = 1;
   */
  inter?: Inter;
};

/**
 * Describes the message proton.v1.inter.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 2);

/**
 * @generated from message proton.v1.inter.ListRequest
 */
export type ListRequest = Message<"proton.v1.inter.ListRequest"> & {
};

/**
 * Describes the message proton.v1.inter.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 3);

/**
 * @generated from message proton.v1.inter.ListResponse
 */
export type ListResponse = Message<"proton.v1.inter.ListResponse"> & {
  /**
   * @generated from field: repeated proton.v1.inter.Inter inters = 1;
   */
  inters: Inter[];
};

/**
 * Describes the message proton.v1.inter.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 4);

/**
 * @generated from message proton.v1.inter.CreateRequest
 */
export type CreateRequest = Message<"proton.v1.inter.CreateRequest"> & {
  /**
   * @generated from field: proton.v1.inter.InterConfig config = 1;
   */
  config?: InterConfig;
};

/**
 * Describes the message proton.v1.inter.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 5);

/**
 * @generated from message proton.v1.inter.CreateResponse
 */
export type CreateResponse = Message<"proton.v1.inter.CreateResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proton.v1.inter.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 6);

/**
 * @generated from message proton.v1.inter.UpdateRequest
 */
export type UpdateRequest = Message<"proton.v1.inter.UpdateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: proton.v1.inter.InterConfig config = 2;
   */
  config?: InterConfig;
};

/**
 * Describes the message proton.v1.inter.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 7);

/**
 * @generated from message proton.v1.inter.UpdateResponse
 */
export type UpdateResponse = Message<"proton.v1.inter.UpdateResponse"> & {
};

/**
 * Describes the message proton.v1.inter.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 8);

/**
 * @generated from message proton.v1.inter.DeleteRequest
 */
export type DeleteRequest = Message<"proton.v1.inter.DeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proton.v1.inter.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 9);

/**
 * @generated from message proton.v1.inter.DeleteResponse
 */
export type DeleteResponse = Message<"proton.v1.inter.DeleteResponse"> & {
};

/**
 * Describes the message proton.v1.inter.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_proton_v1_inter_message, 10);

